language: php

dist: trusty

php:
  - 7.2

addons:
  firefox: latest
  chrome: stable
  browserstack:
      forcelocal: true
      username: benfisher4
      access_key: mVjnFtMSD3V8eGxaeorF

env:
  global:
    - SELENIUM_SERVER_VERSION="3.8.1"
    - CHROMEDRIVER_VERSION="2.35"
    - GECKODRIVER_VERSION="0.19.1"
  matrix:
    - BROWSER=firefox
    - BROWSER=chrome

test:
    pre:
    # Download the browserstack binary file
    - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    # Unzip the browserstack binary file
    - unzip BrowserStackLocal-linux-x64.zip
    # Run the file with your access key
    - ./BrowserStackLocal mVjnFtMSD3V8eGxaeorF > /dev/null &
    - sleep 10

matrix:
  include:
    - php: 7.2
      env: BROWSER=microsoftedge BROWSERSTACK=1 # run tests in MicrosoftEdge on BrowserStack cloud
      install:
        - composer install --no-interaction
      before_script: ~
      script:
        - ./vendor/bin/steward run production $BROWSER -vvv --server-url=https://benfisher4:mVjnFtMSD3V8eGxaeorF@hub-cloud.browserstack.com/wd/hub --capability="browser:IE" --capability="browser_version:11.0" --capability="os:Windows" --capability="os_version:10" --capability="resolution:1024x768"
      after_script: ~
    - php: 7.2
      env: BROWSER=firefox BROWSERSTACK=1 # run tests in Firefox on BrowserStack cloud
      install:
        - composer install --no-interaction
      before_script: ~
      script:
        - ./vendor/bin/steward run production $BROWSER -vvv --server-url=https://benfisher4:mVjnFtMSD3V8eGxaeorF@hub-cloud.browserstack.com/wd/hub --capability="browser:IE" --capability="browser_version:11.0" --capability="os:Windows" --capability="os_version:10" --capability="resolution:1024x768"
      after_script: ~
  allow_failures:
    - env: BROWSER=firefox
    - env: BROWSER=phantomjs

install:
  - composer install --no-interaction # Install Steward and its dependencies
  - SELENIUM_PATH=$(./vendor/bin/steward install $SELENIUM_SERVER_VERSION --no-interaction) # Download the Selenium standalone server jar file
  - echo "Selenium server path:" $SELENIUM_PATH
  - if [ "$BROWSER" = "chrome" ]; then mkdir chromedriver; wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; unzip chromedriver_linux64 -d chromedriver; fi
  - if [ "$BROWSER" = "chrome" ]; then export CHROMEDRIVER_PATH=./chromedriver/chromedriver; fi
  - if [ "$BROWSER" = "firefox" ]; then mkdir geckodriver; wget -q -t 3 https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz; tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver; fi
  - if [ "$BROWSER" = "firefox" ]; then export GECKODRIVER_PATH=./geckodriver/geckodriver; fi

before_script:
  - java -jar $SELENIUM_PATH -role hub -enablePassThrough false -log selenium-server.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for selenium-server to start...; done;

  # Start Chrome on first Selenium node
  - if [ "$BROWSER" = "chrome" ]; then java -Dwebdriver.chrome.driver="$CHROMEDRIVER_PATH" -jar $SELENIUM_PATH -role node -port 8910 -log selenium-node-1.log -enablePassThrough false & fi

  # Start Firefox on first Selenium node
  - if [ "$BROWSER" = "firefox" ]; then Xvfb :99 -nolisten tcp -ac -screen 0 1280x1024x24 & fi
  - if [ "$BROWSER" = "firefox" ]; then export DISPLAY=:99.0; fi
  - if [ "$BROWSER" = "firefox" ]; then java -Dwebdriver.gecko.driver="$GECKODRIVER_PATH" -jar $SELENIUM_PATH -role node -port 8910 -maxSession 1 -log selenium-node-1.log -enablePassThrough false & fi

  # Start Firefox on second Selenium node
  - if [ "$BROWSER" = "firefox" ]; then Xvfb :98 -nolisten tcp -ac -screen 0 1280x1024x24 & fi
  - if [ "$BROWSER" = "firefox" ]; then export DISPLAY=:98.0; fi
  - if [ "$BROWSER" = "firefox" ]; then java -Dwebdriver.gecko.driver="$GECKODRIVER_PATH" -jar $SELENIUM_PATH -role node -port 8911 -maxSession 1 -log selenium-node-2.log -enablePassThrough false  & fi

  - sleep 3 # wait until browsers starts

script:
  - ./vendor/bin/steward run dev $BROWSER -vvv # Run the tests in $BROWSER and specify `dev` as an environment name

after_script:
  - ./vendor/bin/steward results -vvv
  - cat selenium-server.log
  - cat selenium-node-1.log
  - cat selenium-node-2.log

cache:
  directories:
    - $HOME/.composer/cache
