language: php

dist: trusty

php:
  - 7.2

addons:
  firefox: latest
  chrome: stable
  browserstack:
      username: "benfisher4"
      access_key: "mVjnFtMSD3V8eGxaeorF"
      forcelocal: true

env:
  global:
    - SELENIUM_SERVER_VERSION="3.8.1"
    - CHROMEDRIVER_VERSION="2.35"
    - GECKODRIVER_VERSION="0.19.1"
  matrix:
    - BROWSER=chrome

install:
  - composer install --no-interaction # Install Steward and its dependencies
  - SELENIUM_PATH=$(./vendor/bin/steward install $SELENIUM_SERVER_VERSION --no-interaction) # Download the Selenium standalone server jar file
  - echo "Selenium server path:" $SELENIUM_PATH
  - if [ "$BROWSER" = "chrome" ]; then mkdir chromedriver; wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; unzip chromedriver_linux64 -d chromedriver; fi
  - if [ "$BROWSER" = "chrome" ]; then export CHROMEDRIVER_PATH=./chromedriver/chromedriver; fi

before_script:
  - java -jar $SELENIUM_PATH -role hub -enablePassThrough false -log selenium-server.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Carthook :: Waiting for selenium-server to start...; done;

  # Start Chrome on first Selenium node
  - if [ "$BROWSER" = "chrome" ]; then java -Dwebdriver.chrome.driver="$CHROMEDRIVER_PATH" -jar $SELENIUM_PATH -role node -port 8910 -log selenium-node-1.log -enablePassThrough false & fi
  - sleep 3 # wait until browser(s) starts

script:
  - ./vendor/bin/steward run dev $BROWSER -vvv # Run the tests in $BROWSER and specify `dev` as an environment name

after_script:
  - ./vendor/bin/steward results -vvv
  - cat selenium-server.log
  - cat selenium-node-1.log

cache:
  directories:
    - $HOME/.composer/cache
